#!/bin/sh

bspc rule -r "*"

monitors=$(bspc query -M | wc -l)

if [[ $monitors -eq "2" ]]; then
   autorandr -fc docked
fi

# Border/gap settings
bspc config border_width								2
bspc config window_gap									10
bspc config split_ratio									0.50
bspc config single_monocle							    true
bspc config borderless_monocle				        	true
bspc config gapless_monocle						    	true

# Border colors
bspc config normal_border_color				        	"#282828"
bspc config focused_border_color			        	"#b8bb26"

# Padding settings
bspc config top_padding									24
bspc config right_padding								0
bspc config left_padding								0
bspc config bottom_padding						    	0

# Mouse settings
bspc config pointer_modifier					    	shift
bspc config pointer_action1						    	move
bspc config pointer_action3						    	resize_corner

# Pointer settings
bspc config focus_follows_pointer			        	true

# Remove inactive monitors
bspc config remove_disabled_monitors	        	    true
bspc config remove_unplugged_monitors	            	true

# Create workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc desktop Desktop --remove

# Program rules
bspc rule -a Zathura									state=tiled
bspc rule -a firefox                                    desktop='^1' follow=on
